import "./styles.css";
import "./tailwind.css";
import { Inter } from "next/font/google";

import { SectionProvider } from "@/components/sectionContext";
import WalletConnect from "@/components/walletConnect/walletConnect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "UNDOXXED",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <div className="min-h-screen antialiased bg-ob-blackbg">
          <SectionProvider>
            <WalletConnect>{children}</WalletConnect>
          </SectionProvider>
        </div>
      </body>
    </html>
  );
}
