import "./globals.css";
import "./font.css";
import { Inter } from "next/font/google";

import { SectionProvider } from "@/components/sectionContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SectionProvider>{children}</SectionProvider>
      </body>
    </html>
  );
}
