import "./globals.css";
import "./font.css";
import { Inter } from "next/font/google";
import WalletConnect from "@/components/walletConnect/walletConnect";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function MintLayout({ children }) {
  return <WalletConnect>{children}</WalletConnect>;
}
